version: '3.9'

services:
  web:
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./app/.nginx.conf:/etc/nginx/conf.d/.tasty.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
  mysql:
    image: mysql:8.0
    ports:
    - 3306:3306
    volumes:
    - /var/lib/mysql
    environment:
        MYSQL_DATABASE: laravel
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_USER: anpq
        MYSQL_PASSWORD: 123456